# Kubernetes deployment YAML file to quickly deploy a simple container
# to Kubernetes. For more information, see:
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/lagroucedric/mlops-exam-1-frontend:latest
        ports:
        - containerPort: 80
          name: http
      #pull secret credentials
      imagePullSecrets:
        - name: regcred
