#add service NodePort to open port 30001
apiVersion: v1
kind: Service
metadata:
  name: svcfrontend
  labels:
    app: svcfrontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    app: frontend