name: MLOps Automation

on:
  push:
    branches: [ master ]

jobs:
  #build docker file and push to ghcr
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get SHA
       run: echo "GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV 
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./api/exam-1-dockerfile
          push: true
          tags: ghcr.io/lagroucedric/mlops-exam-1-backend:latest
    #build another dockerfile and psuh to ghcr
    
      - name: Build2
        id: docker_build2
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./frontend/frontend-dockerfile
          push: true
          tags:  ghcr.io/lagroucedric/mlops-exam-1-frontend:latest




    