name: MLOps Automation

on:
  push:
    branches: [ master ]

jobs:
  #build docker file and push to ghcr
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./api/exam-1-dockerfile
          push: true
          tags: ghcr.io/lagroucedric/mlops-exam-1-backend:${{ env.GIT_SHA }}
    #build another dockerfile and psuh to ghcr
    
      - name: Build2
        id: docker_build2
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./frontend/frontend-dockerfile
          push: true
          image: ghcr.io/lagroucedric/mlops-exam-1-frontend
          tags: |
            type=ref,event=branch
            type=sha




    